#include "sosdata.h"
//-------------------------------------------------------------------------------------------------

tSOSSampleEntry _lpSOSSampleList[5][32] =     //000B65F0
{
  {
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u }
  },
  {
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u }
  },
  {
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u }
  },
  {
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u }
  },
  {
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u },
    { NULL, 0u, 0u }
  }
};

//-------------------------------------------------------------------------------------------------